name: apply-terraform

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"

jobs:
  apply_terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.4

      - name: Apply Terraform changes
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve

