name: Manage AWS Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose whether to apply or destroy Terraform resources'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  apply_terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.4

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply / Destroy
        run: |
          cd terraform
          if [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            terraform destroy -auto-approve
          else
            terraform apply -auto-approve
          fi
