name: Push API Image to ECR

on:
  push:
    branches:
      - main
    paths:
      - "api/**"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Build and push Docker image to ECR
        run: |
          docker build -t voice-hue api
          docker tag voice-hue:latest public.ecr.aws/${{ secrets.REGISTRY_ALIAS }}/projects/voice-hue:latest
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/${{ secrets.REGISTRY_ALIAS }}/projects/voice-hue
          docker push public.ecr.aws/${{ secrets.REGISTRY_ALIAS }}/projects/voice-hue:latest
